# Generated by Django 4.2.5 on 2023-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='placeholders',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
